/**
      * 
      * ! DON'T EDIT Directly!!!
      * Generated by Esbuild using Meact's custom plugin "build-memix-build-map-plugin"
      * 
    */ 
    import * as _mainLayout from "../../server/api/routes/_mainLayout.ts";
import * as upvoted from "../../server/api/routes/upvoted.ts";
import * as threads from "../../server/api/routes/threads.ts";
import * as submitted from "../../server/api/routes/submitted.ts";
import * as noobstories from "../../server/api/routes/noobstories.ts";
import * as noobcomments from "../../server/api/routes/noobcomments.ts";
import * as newpoll from "../../server/api/routes/newpoll.ts";
import * as lists from "../../server/api/routes/lists.ts";
import * as leaders from "../../server/api/routes/leaders.ts";
import * as jobs from "../../server/api/routes/jobs.ts";
import * as index from "../../server/api/routes/index.ts";
import * as hidden from "../../server/api/routes/hidden.ts";
import * as front from "../../server/api/routes/front.ts";
import * as from from "../../server/api/routes/from.ts";
import * as formatdoc from "../../server/api/routes/formatdoc.ts";
import * as forgot from "../../server/api/routes/forgot.ts";
import * as favorites from "../../server/api/routes/favorites.ts";
import * as dmca from "../../server/api/routes/dmca.ts";
import * as changepw from "../../server/api/routes/changepw.ts";
import * as bookmarklet from "../../server/api/routes/bookmarklet.ts";
import * as bestcomments from "../../server/api/routes/bestcomments.ts";
import * as active from "../../server/api/routes/active.ts";

    interface IComponentServerSideHandlers {
      metaFn?: Function;
      loaderFn?: Function;
      actionFn?: Function;
    }
    
    export const mapOfComponentNameToServerSideHandlers: Map<
      string,
      IComponentServerSideHandlers
    > = new Map([
      [
      _mainLayout.componentName,
      {
        
        loaderFn: _mainLayout.loader,
        
      },
    ],
[
      upvoted.componentName,
      {
        metaFn: upvoted.meta,
        
        
      },
    ],
[
      threads.componentName,
      {
        metaFn: threads.meta,
        
        
      },
    ],
[
      submitted.componentName,
      {
        metaFn: submitted.meta,
        
        
      },
    ],
[
      noobstories.componentName,
      {
        metaFn: noobstories.meta,
        
        
      },
    ],
[
      noobcomments.componentName,
      {
        metaFn: noobcomments.meta,
        
        
      },
    ],
[
      newpoll.componentName,
      {
        metaFn: newpoll.meta,
        
        
      },
    ],
[
      lists.componentName,
      {
        metaFn: lists.meta,
        
        
      },
    ],
[
      leaders.componentName,
      {
        metaFn: leaders.meta,
        
        
      },
    ],
[
      jobs.componentName,
      {
        metaFn: jobs.meta,
        loaderFn: jobs.loader,
        
      },
    ],
[
      index.componentName,
      {
        metaFn: index.meta,
        loaderFn: index.loader,
        
      },
    ],
[
      hidden.componentName,
      {
        metaFn: hidden.meta,
        
        
      },
    ],
[
      front.componentName,
      {
        metaFn: front.meta,
        
        
      },
    ],
[
      from.componentName,
      {
        metaFn: from.meta,
        
        
      },
    ],
[
      formatdoc.componentName,
      {
        metaFn: formatdoc.meta,
        
        
      },
    ],
[
      forgot.componentName,
      {
        metaFn: forgot.meta,
        
        
      },
    ],
[
      favorites.componentName,
      {
        metaFn: favorites.meta,
        
        
      },
    ],
[
      dmca.componentName,
      {
        metaFn: dmca.meta,
        
        
      },
    ],
[
      changepw.componentName,
      {
        metaFn: changepw.meta,
        
        
      },
    ],
[
      bookmarklet.componentName,
      {
        metaFn: bookmarklet.meta,
        
        
      },
    ],
[
      bestcomments.componentName,
      {
        metaFn: bestcomments.meta,
        
        
      },
    ],
[
      active.componentName,
      {
        metaFn: active.meta,
        
        
      },
    ],
    ]);