/**
      * 
      * ! DON'T EDIT Directly!!!
      * Generated by running framework.build.ts
      *  
    */
    import * as _mainLayout from "../../server/api/_mainLayout.ts";
import * as upvoted from "../../server/api/upvoted.ts";
import * as threads from "../../server/api/threads.ts";
import * as submitted from "../../server/api/submitted.ts";
import * as noobstories from "../../server/api/noobstories.ts";
import * as noobcomments from "../../server/api/noobcomments.ts";
import * as newpoll from "../../server/api/newpoll.ts";
import * as lists from "../../server/api/lists.ts";
import * as leaders from "../../server/api/leaders.ts";
import * as jobs from "../../server/api/jobs.ts";
import * as item from "../../server/api/item.ts";
import * as index from "../../server/api/index.ts";
import * as hidden from "../../server/api/hidden.ts";
import * as front from "../../server/api/front.ts";
import * as from from "../../server/api/from.ts";
import * as formatdoc from "../../server/api/formatdoc.ts";
import * as forgot from "../../server/api/forgot.ts";
import * as favorites from "../../server/api/favorites.ts";
import * as dmca from "../../server/api/dmca.ts";
import * as changepw from "../../server/api/changepw.ts";
import * as bookmarklet from "../../server/api/bookmarklet.ts";
import * as bestcomments from "../../server/api/bestcomments.ts";
import * as active from "../../server/api/active.ts";

    export const mapOfComponentNameToServerSideHandlers = new Map([
      [
      _mainLayout.componentName,
      {
        componentName: _mainLayout.componentName,
loader: _mainLayout.loader,
      },
    ],
[
      "upvoted",
      {
        componentName: upvoted.componentName,
meta: upvoted.meta,
      },
    ],
[
      "threads",
      {
        componentName: threads.componentName,
meta: threads.meta,
      },
    ],
[
      "submitted",
      {
        componentName: submitted.componentName,
meta: submitted.meta,
      },
    ],
[
      "noobstories",
      {
        componentName: noobstories.componentName,
meta: noobstories.meta,
      },
    ],
[
      "noobcomments",
      {
        componentName: noobcomments.componentName,
meta: noobcomments.meta,
      },
    ],
[
      "newpoll",
      {
        componentName: newpoll.componentName,
meta: newpoll.meta,
      },
    ],
[
      "lists",
      {
        componentName: lists.componentName,
meta: lists.meta,
      },
    ],
[
      "leaders",
      {
        componentName: leaders.componentName,
meta: leaders.meta,
      },
    ],
[
      "jobs",
      {
        componentName: jobs.componentName,
meta: jobs.meta,
loader: jobs.loader,
      },
    ],
[
      "item",
      {
        componentName: item.componentName,
meta: item.meta,
loader: item.loader,
      },
    ],
[
      "index",
      {
        componentName: index.componentName,
meta: index.meta,
loader: index.loader,
      },
    ],
[
      "hidden",
      {
        componentName: hidden.componentName,
meta: hidden.meta,
      },
    ],
[
      "front",
      {
        componentName: front.componentName,
meta: front.meta,
      },
    ],
[
      "from",
      {
        componentName: from.componentName,
meta: from.meta,
      },
    ],
[
      "formatdoc",
      {
        componentName: formatdoc.componentName,
meta: formatdoc.meta,
      },
    ],
[
      "forgot",
      {
        componentName: forgot.componentName,
meta: forgot.meta,
      },
    ],
[
      "favorites",
      {
        componentName: favorites.componentName,
meta: favorites.meta,
      },
    ],
[
      "dmca",
      {
        componentName: dmca.componentName,
meta: dmca.meta,
      },
    ],
[
      "changepw",
      {
        componentName: changepw.componentName,
meta: changepw.meta,
      },
    ],
[
      "bookmarklet",
      {
        componentName: bookmarklet.componentName,
meta: bookmarklet.meta,
      },
    ],
[
      "bestcomments",
      {
        componentName: bestcomments.componentName,
meta: bestcomments.meta,
      },
    ],
[
      "active",
      {
        componentName: active.componentName,
meta: active.meta,
      },
    ],
    ]);