import { glob } from "glob";
import path from "path";
import { writeFileSync } from "fs";
import { SERVER_API_DIRECTORY } from "../constants/fileAndDirectoryNameAndPaths.js";

export async function buildMeactFrameworkServerSideHandlersMap() {
  console.log("Meact app's server side handlers have to be registered...");

  const routeFiles = glob.sync(`${SERVER_API_DIRECTORY}/*.ts`);

  const imports = [];
  const mapEntries = [];

  for (const file of routeFiles) {
    const fileName = path.basename(file, ".ts");

    const importPath = path.join("../..", file).replace(/\\/g, "/"); // Make the path relative and compatible with all OS

    const importStatementForThisFile = `import * as ${fileName} from "${importPath}";`;
    imports.push(importStatementForThisFile);

    console.log("importPath, importPath", importPath);

    // Dynamically import the module
    const moduleExports = await import(importPath); // relative path

    const mapEntry = `[
      ${
        fileName.startsWith("_") ? `${fileName}.componentName` : `"${fileName}"`
      },
      {
        ${`"componentName": ${fileName}.componentName,`} 
        ${"meta" in moduleExports ? `metaFn: ${fileName}.meta,` : ""}
        ${"loader" in moduleExports ? `loaderFn: ${fileName}.loader,` : ""}
        ${"action" in moduleExports ? `actionFn: ${fileName}.action,` : ""}
      },
    ],`;

    mapEntries.push(mapEntry);
  }

  const outputContent = `
    /**
      * 
      * ! DON'T EDIT Directly!!!
      * Generated by running framework.build.ts
      *  
    */
    import { MeactMeta } from "@meact-framework";
    ${imports.join("\n")}

    interface IComponentServerSideHandlers {
      componentName: string;
      metaFn?: MeactMeta;
      loaderFn?: Function;
      actionFn?: Function;
    }
    
    export const mapOfComponentNameToServerSideHandlers: Map<
      string,
      IComponentServerSideHandlers
    > = new Map([
      ${mapEntries.join("\n")}
    ]);
  `;

  writeFileSync("./build.ts", outputContent.trim());
  console.log(
    "Meact app's server side handlers have been registered successfully."
  );
}

buildMeactFrameworkServerSideHandlersMap()
  .then(() => {
    console.log("Successfuly built Meact app's server-side handlers map");
    process.exit(); // Explicitly terminate the process
  })
  .catch((err) => {
    console.error(
      "Error in building Meact app's server-side handlers map:",
      err
    );
    process.exit(1); // Exit with a non-zero status code on error
  });
