/**
      * 
      * ! DON'T EDIT Directly!!!
      * Generated by running framework.build.ts
      *  
    */
    import * as active from "../../server/api/active.ts";
import * as ask from "../../server/api/ask.ts";
import * as best from "../../server/api/best.ts";
import * as bestcomments from "../../server/api/bestcomments.ts";
import * as bookmarklet from "../../server/api/bookmarklet.ts";
import * as changepw from "../../server/api/changepw.ts";
import * as dmca from "../../server/api/dmca.ts";
import * as favorites from "../../server/api/favorites.ts";
import * as formatdoc from "../../server/api/formatdoc.ts";
import * as from from "../../server/api/from.ts";
import * as front from "../../server/api/front.ts";
import * as hidden from "../../server/api/hidden.ts";
import * as index from "../../server/api/index.ts";
import * as item from "../../server/api/item.ts";
import * as jobs from "../../server/api/jobs.ts";
import * as leaders from "../../server/api/leaders.ts";
import * as lists from "../../server/api/lists.ts";
import * as login from "../../server/api/login.ts";
import * as logout from "../../server/api/logout.ts";
import * as newcomments from "../../server/api/newcomments.ts";
import * as newest from "../../server/api/newest.ts";
import * as newpoll from "../../server/api/newpoll.ts";
import * as noobcomments from "../../server/api/noobcomments.ts";
import * as noobstories from "../../server/api/noobstories.ts";
import * as register from "../../server/api/register.ts";
import * as show from "../../server/api/show.ts";
import * as shownew from "../../server/api/shownew.ts";
import * as submitted from "../../server/api/submitted.ts";
import * as threads from "../../server/api/threads.ts";
import * as upvoted from "../../server/api/upvoted.ts";
import * as user from "../../server/api/user.ts";
import * as vote from "../../server/api/vote.ts";
import * as xuser from "../../server/api/xuser.ts";
import * as _mainLayout from "../../server/api/_mainLayout.ts";

    export const mapOfComponentNameToServerSideHandlers = new Map([
      [
      "active",
      {
        isPage: true,
        componentName: active.componentName,
meta: active.meta,
      },
    ],
[
      "ask",
      {
        isPage: true,
        componentName: ask.componentName,
meta: ask.meta,
loader: ask.loader,
      },
    ],
[
      "best",
      {
        isPage: true,
        componentName: best.componentName,
meta: best.meta,
loader: best.loader,
      },
    ],
[
      "bestcomments",
      {
        isPage: true,
        componentName: bestcomments.componentName,
meta: bestcomments.meta,
      },
    ],
[
      "bookmarklet",
      {
        isPage: true,
        componentName: bookmarklet.componentName,
meta: bookmarklet.meta,
      },
    ],
[
      "changepw",
      {
        isPage: true,
        componentName: changepw.componentName,
meta: changepw.meta,
      },
    ],
[
      "dmca",
      {
        isPage: true,
        componentName: dmca.componentName,
meta: dmca.meta,
      },
    ],
[
      "favorites",
      {
        isPage: true,
        componentName: favorites.componentName,
meta: favorites.meta,
      },
    ],
[
      "formatdoc",
      {
        isPage: true,
        componentName: formatdoc.componentName,
meta: formatdoc.meta,
      },
    ],
[
      "from",
      {
        isPage: true,
        componentName: from.componentName,
meta: from.meta,
      },
    ],
[
      "front",
      {
        isPage: true,
        componentName: front.componentName,
meta: front.meta,
      },
    ],
[
      "hidden",
      {
        isPage: true,
        componentName: hidden.componentName,
meta: hidden.meta,
      },
    ],
[
      "index",
      {
        isPage: true,
        componentName: index.componentName,
meta: index.meta,
loader: index.loader,
      },
    ],
[
      "item",
      {
        isPage: true,
        componentName: item.componentName,
meta: item.meta,
loader: item.loader,
      },
    ],
[
      "jobs",
      {
        isPage: true,
        componentName: jobs.componentName,
meta: jobs.meta,
loader: jobs.loader,
      },
    ],
[
      "leaders",
      {
        isPage: true,
        componentName: leaders.componentName,
meta: leaders.meta,
      },
    ],
[
      "lists",
      {
        isPage: true,
        componentName: lists.componentName,
meta: lists.meta,
      },
    ],
[
      "login",
      {
        isPage: true,
        componentName: login.componentName,
meta: login.meta,
loader: login.loader,
action: login.action,
      },
    ],
[
      "logout",
      {
        isPage: null,
        componentName: logout.componentName,
action: logout.action,
      },
    ],
[
      "newcomments",
      {
        isPage: true,
        componentName: newcomments.componentName,
meta: newcomments.meta,
loader: newcomments.loader,
      },
    ],
[
      "newest",
      {
        isPage: true,
        componentName: newest.componentName,
meta: newest.meta,
loader: newest.loader,
      },
    ],
[
      "newpoll",
      {
        isPage: true,
        componentName: newpoll.componentName,
meta: newpoll.meta,
      },
    ],
[
      "noobcomments",
      {
        isPage: true,
        componentName: noobcomments.componentName,
meta: noobcomments.meta,
      },
    ],
[
      "noobstories",
      {
        isPage: true,
        componentName: noobstories.componentName,
meta: noobstories.meta,
      },
    ],
[
      "register",
      {
        isPage: null,
        componentName: register.componentName,
action: register.action,
      },
    ],
[
      "show",
      {
        isPage: true,
        componentName: show.componentName,
meta: show.meta,
loader: show.loader,
      },
    ],
[
      "shownew",
      {
        isPage: true,
        componentName: shownew.componentName,
meta: shownew.meta,
loader: shownew.loader,
      },
    ],
[
      "submitted",
      {
        isPage: true,
        componentName: submitted.componentName,
meta: submitted.meta,
      },
    ],
[
      "threads",
      {
        isPage: true,
        componentName: threads.componentName,
meta: threads.meta,
      },
    ],
[
      "upvoted",
      {
        isPage: true,
        componentName: upvoted.componentName,
meta: upvoted.meta,
      },
    ],
[
      "user",
      {
        isPage: true,
        componentName: user.componentName,
meta: user.meta,
loader: user.loader,
      },
    ],
[
      "vote",
      {
        isPage: null,
        componentName: vote.componentName,
action: vote.action,
      },
    ],
[
      "xuser",
      {
        isPage: null,
        componentName: xuser.componentName,
action: xuser.action,
      },
    ],
[
      _mainLayout.componentName,
      {
        isPage: false,
        componentName: _mainLayout.componentName,
loader: _mainLayout.loader,
      },
    ],
    ]);